// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rivltbbynuqlkmzufpai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdmx0YmJ5bnVxbGttenVmcGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjUwMDcsImV4cCI6MjA2NjgwMTAwN30.YSpaHlZydteUxs3AsVApZ9HoFlTcKah51XyBHeqtlK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});